server:
  port: 8080

spring:
  application:
    name: assignment
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # With production database there would be a different URL
    username: postgres # With production database the username would come from Kubernetes secrets or similar
    password: password # With production database the password would come from Kubernetes secrets or similar
  jpa:
    show-sql: true
    driverClassName: org.hibernate.dialect.PostgreSQL81Dialect

  ## Flyway config
  flyway:
    baseline-version: 1
    baseline-on-migrate: true
