INSERT INTO sector (id, sectorname, parentid) VALUES (1, 'Manufacturing', null) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (19, 'Construction materials', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (18, 'Electronics and Optics', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (6, 'Food and Beverage', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (342, 'Bakery & confectionery products', 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (43, 'Beverages', 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (42, 'Fish & fish products', 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (40, 'Meat & meat products', 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (39, 'Milk & dairy products', 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (437, 'Other', 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (378, 'Sweets & snack food', 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (13, 'Furniture', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (389, 'Bathroom/sauna', 13) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (385, 'Bedroom', 13) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (390, 'Children’s room', 13) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (98, 'Kitchen', 13) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (101, 'Living room', 13) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (392, 'Office', 13) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (394, 'Other (Furniture)', 13) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (341, 'Outdoor', 13) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (99, 'Project furniture', 13) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (12, 'Machinery', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (94, 'Machinery components', 12) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (91, 'Machinery equipment/tools', 12) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (224, 'Manufacture of machinery', 12) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (97, 'Maritime', 12) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (271, 'Aluminium and steel workboats', 97) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (269, 'Boat/Yacht building', 97) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (230, 'Ship repair and conversion', 97) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (93, 'Metal structures', 12) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (508, 'Other', 12) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (227, 'Repair and maintenance service', 12) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (11, 'Metalworking', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (67, 'Construction of metal structures', 11) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (263, 'Houses and buildings', 11) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (267, 'Metal products', 11) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (542, 'Metal works', 11) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (75, 'CNC-machining', 542) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (62, 'Forgings, Fasteners', 542) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (69, 'Gas, Plasma, Laser cutting', 542) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (66, 'MIG, TIG, Aluminum welding', 542) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (9, 'Plastic and Rubber', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (54, 'Packaging', 9) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (556, 'Plastic goods', 9) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (559, 'Plastic processing technology', 9) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (55, 'Blowing', 559) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (57, 'Moulding', 559) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (53, 'Plastics welding and processing', 559) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (560, 'Plastic profiles', 9) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (5, 'Printing', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (148, 'Advertising', 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (150, 'Book/Periodicals printing', 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (145, 'Labelling and packaging printing', 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (7, 'Textile and Clothing', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (44, 'Clothing', 7) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (45, 'Textile', 7) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (8, 'Wood', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (337, 'Other (Wood)', 8) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (51, 'Wooden building materials', 8) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (47, 'Wooden houses', 8) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (3, 'Other', null) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (37, 'Creative industries', 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (29, 'Energy technology', 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (33, 'Environment', 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (2, 'Service', null) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (25, 'Business services', 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (35, 'Engineering', 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (28, 'Information Technology and Telecommunications', 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (581, 'Data processing, Web portals, E-marketing', 28) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (576, 'Programming, Consultancy', 28) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (121, 'Software, Hardware', 28) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (122, 'Telecommunications', 28) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (22, 'Tourism', 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (141, 'Translation services', 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (21, 'Transport and Logistics', 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (111, 'Air', 21) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (114, 'Rail', 21) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (112, 'Road', 21) ON CONFLICT (id) DO NOTHING;
INSERT INTO sector (id, sectorname, parentid) VALUES (113, 'Water', 21) ON CONFLICT (id) DO NOTHING;
